package main

import (
	"fmt"
	"os"

	"github.com/devlongs/evm-assembler/asm"
	"github.com/devlongs/evm-assembler/evm"
	"github.com/devlongs/evm-assembler/internal/utils"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: assembler <input file>")
		return
	}

	fileContent, err := utils.ReadFile(os.Args[1])
	if err != nil {
		fmt.Println("Error reading file:", err)
		return
	}

	instructions, err := asm.ParseAssembly(fileContent)
	if err != nil {
		fmt.Println("Error parsing assembly:", err)
		return
	}

	bytecode, err := evm.GenerateBytecode(instructions)
	if err != nil {
		fmt.Println("Error generating bytecode:", err)
		return
	}

	fmt.Printf("Generated Bytecode: %x\n", bytecode)
}
